#!/usr/bin/env python3
"""Generate bundle-data.js: the "same up to ___" ladder per function.

For every function of the chosen subjects, compute its equivalence bundle at
each dial stop — identical in every detail, up to renaming, up to renaming &
types, same shape — and record which members each loosening step admits.
Emitted for both the yul-fn level and the derived yulssa-fn level. Grouping
on dimension-digest tuples matches the facet address by construction.

Usage: generate-bundle-data.py <corpus-dir> <out.js> <label>=<file.jsonl> ...
"""
import json, sys, glob, os, collections

corpus_dir, out_path = sys.argv[1], sys.argv[2]
subjects = [arg.split("=", 1) for arg in sys.argv[3:]]

UNITS = ("yul-fn", "yulssa-fn")
DIMS = ("structure", "names", "constants", "types", "trace_events")
STOPS = [  # (id, kept dimensions, human label)
    ("all", DIMS, "the same in every detail"),
    ("nb", ("structure", "constants", "types", "trace_events"), "the same up to renaming"),
    ("sc", ("structure", "constants"), "the same up to renaming & types"),
    ("st", ("structure",), "the same shape — names, constants, types all forgotten"),
]

sf_labels = {"sf_1_7a492a6c.jsonl": "fartdog", "sf_1_c4eca49a.jsonl": "Token",
             "sf_1_entrypoint.jsonl": "EntryPoint", "sf_1_poolmanager.jsonl": "PoolManager",
             "sf_1_permit2.jsonl": "Permit2", "sf_1_231b0ee1.jsonl": "ENS PublicResolver"}
def home(fname, owner):
    if fname in sf_labels: return sf_labels[fname]
    parts = owner.split(":")
    return parts[1].split("/")[-1] if len(parts) > 1 else fname

rows_by_unit = {u: [] for u in UNITS}
for path in sorted(glob.glob(os.path.join(corpus_dir, "*.jsonl"))):
    fname = os.path.basename(path)
    with open(path) as f:
        for line in f:
            r = json.loads(line)
            if r.get("record") == "digest" and r.get("unit") in rows_by_unit and r.get("mode") == "shape":
                d = r["digests"]
                rows_by_unit[r["unit"]].append({
                    "name": r["name"], "home": home(fname, r["owner"]),
                    "file": fname, "owner": r["owner"], "nodes": r.get("node_count", 0),
                    "keys": {sid: tuple(d.get(k, "∅") for k in kept) for sid, kept, _ in STOPS}})

def subject_row(unit, row):
    # yul-fn: unoptimized ir pipeline only; yulssa-fn: one row per setting already
    return ":ir:" in row["owner"] if unit == "yul-fn" else True

out = {"stops": [{"id": sid, "label": label} for sid, _, label in STOPS], "units": {}}
for unit in UNITS:
    rows = rows_by_unit[unit]
    index = {sid: collections.defaultdict(list) for sid, _, _ in STOPS}
    for i, row in enumerate(rows):
        for sid in index:
            index[sid][row["keys"][sid]].append(i)

    def ladder(i):
        row, out_l, prev = rows[i], [], set()
        for sid, _, label in STOPS:
            members = [j for j in index[sid][row["keys"][sid]] if j != i]
            admitted = [j for j in members if j not in prev]
            homes = collections.Counter(rows[j]["home"] for j in members)
            out_l.append({"stop": sid, "others": len(members), "admitted": len(admitted),
                          "homes": [{"home": h, "n": n} for h, n in homes.most_common(6)],
                          "moreHomes": max(0, len(homes) - 6),
                          "samples": [{"name": rows[j]["name"], "home": rows[j]["home"]}
                                      for j in admitted[:8]]})
            prev = set(members)
        return out_l

    unit_subjects = []
    for label, fname in subjects:
        seen, fns = set(), []
        for i, row in enumerate(rows):
            if row["file"] != fname or not subject_row(unit, row) or row["name"] in seen:
                continue
            seen.add(row["name"])
            fns.append({"name": row["name"], "nodes": row["nodes"], "ladder": ladder(i)})
        fns.sort(key=lambda f: -f["ladder"][-1]["others"])
        unit_subjects.append({"label": label, "functions": fns})
    out["units"][unit] = {"rows": len(rows), "subjects": unit_subjects}

with open(out_path, "w") as f:
    f.write("// Generated by generate-bundle-data.py — do not hand-edit.\n")
    f.write("window.RIFFCAT_BUNDLE = ")
    json.dump(out, f, separators=(",", ":"))
    f.write(";\n")
for unit in UNITS:
    for s in out["units"][unit]["subjects"]:
        n = len(s["functions"])
        top = s["functions"][0] if n else None
        print(f"{unit} / {s['label']}: {n} fns" +
              (f"; widest: {top['name']} ({top['ladder'][-1]['others']} others at shape)" if top else ""),
              file=sys.stderr)
