#!/usr/bin/env bash
# Regenerate the explorer's data.js from the staged demo corpus.
#
# The page consumes `riffcat overlap --json` output RAW, on purpose: the JSON
# shape is the co-design surface (what should a "similar contracts" payload
# carry?), so the explorer adapts to it rather than papering over it. The only
# additions are the summary counts, which today print on stderr-adjacent text
# output only — a known gap in the JSON shape.
#
# Run from the repo root after `demo/stage.sh`. Works fully offline.
set -euo pipefail

cd "$(dirname "$0")/../.."
RIFFCAT=${RIFFCAT:-target/release/riffcat}
CORPUS=${CORPUS:-demo/corpus}
OUT="demo/explorer/data.js"
UNIT=yul-fn
MODE=shape

FACETS=(all names-blind structure+constants structure)
PAIRS=(
  "ERC20.sol|SoliditySimpleAmm"
  "Groth16Verifier|PlonkVerifier"
  "SolidityFullMath|SoliditySimpleAmm"
  "ERC20.sol|Escrow"
)

result=$(jq -n --arg unit "$UNIT" --arg mode "$MODE" --arg corpus "$CORPUS" \
  --arg generated "$(date -u +%F)" \
  '{unit: $unit, mode: $mode, corpus: $corpus, generated: $generated, pairs: []}')

for pair in "${PAIRS[@]}"; do
  left=${pair%%|*}
  right=${pair##*|}
  echo "pair: $left vs $right" >&2
  facets_json="{}"
  for facet in "${FACETS[@]}"; do
    rows=$("$RIFFCAT" --corpus "$CORPUS" --json overlap "$left" "$right" \
      --unit "$UNIT" --mode "$MODE" --facet "$facet")
    # A: 68 classes, B: 54 classes, shared: 36, Jaccard 0.419
    summary_line=$("$RIFFCAT" --corpus "$CORPUS" overlap "$left" "$right" \
      --unit "$UNIT" --mode "$MODE" --facet "$facet" | tail -1)
    summary=$(echo "$summary_line" | awk -F'[ ,]+' \
      '{print "{\"a\":" $2 ",\"b\":" $5 ",\"shared\":" $8 ",\"jaccard\":" $10 "}"}')
    facets_json=$(jq --arg facet "$facet" --argjson rows "$rows" --argjson summary "$summary" \
      '. + {($facet): {summary: $summary, rows: $rows}}' <<<"$facets_json")
  done
  result=$(jq --arg left "$left" --arg right "$right" --argjson facets "$facets_json" \
    '.pairs += [{left: $left, right: $right, facets: $facets}]' <<<"$result")
done

{
  echo "// Generated by demo/explorer/generate-data.sh — do not hand-edit."
  echo "// Loaded as a plain script so the page works from file:// (fetch of"
  echo "// local JSON is blocked there); the payload is verbatim riffcat output."
  printf 'window.RIFFCAT_DATA = '
  jq . <<<"$result"
  echo ';'
} >"$OUT"
echo "wrote $OUT" >&2
