#!/usr/bin/env python3
"""Generate triage-data.js: per-function rarity of mainnet contracts vs the corpus.

For each subject contract (a sourcify ingest), classify every yul-fn by
whether its names-blind fingerprint has twins anywhere else in the corpus.
Twins-elsewhere = machinery; no twins = the novel surface an auditor should
actually read. Grouping by the names-blind dimension tuple is exactly the
facet's equality (the facet address is a hash of those same digests).

Usage: generate-triage-data.py <corpus-dir> <out.js> <subject>=<file.jsonl> ...
Subjects' yul-fn rows are taken from the unoptimized `ir` pipeline.
"""
import json, sys, glob, os, collections

corpus_dir, out_path = sys.argv[1], sys.argv[2]
subjects = [arg.split("=", 1) for arg in sys.argv[3:]]

NB_DIMS = ("structure", "constants", "types", "trace_events")  # names-blind

rows_by_file = {}
for path in sorted(glob.glob(os.path.join(corpus_dir, "*.jsonl"))):
    rows = []
    with open(path) as f:
        for line in f:
            r = json.loads(line)
            if r.get("record") == "digest" and r.get("unit") == "yul-fn" and r.get("mode") == "shape":
                d = r["digests"]
                rows.append({
                    "name": r["name"], "owner": r["owner"],
                    "nodes": r.get("node_count", 0),
                    "nb": tuple(d[k] for k in NB_DIMS),
                    "st": d["structure"],
                })
    rows_by_file[os.path.basename(path)] = rows

# label a row's home for twin-evidence chips: local-build owners look like
# "yulir:ERC20.sol:ERC20:ir:noopt", sourcify ones end ":sf"
sf_labels = {fname: label for label, fname in subjects}
extra_sf = {"sf_1_poolmanager.jsonl": "PoolManager", "sf_1_permit2.jsonl": "Permit2",
            "sf_1_231b0ee1.jsonl": "ENS PublicResolver", "sf_1_entrypoint.jsonl": "EntryPoint",
            "sf_1_c4eca49a.jsonl": "Token", "sf_1_7a492a6c.jsonl": "fartdog"}
def home(fname, owner):
    if fname in sf_labels: return sf_labels[fname]
    if fname in extra_sf: return extra_sf[fname]
    parts = owner.split(":")
    return parts[1].split("/")[-1] if len(parts) > 1 else fname

nb_index = collections.defaultdict(list)   # nb key -> [(file, row)]
st_index = collections.defaultdict(list)
for fname, rows in rows_by_file.items():
    for row in rows:
        nb_index[row["nb"]].append((fname, row))
        st_index[row["st"]].append((fname, row))

def classify(subj_file, row):
    def twins(index, key):
        hits = [(f, r) for f, r in index[key] if f != subj_file]
        homes = collections.Counter(home(f, r["owner"]) for f, r in hits)
        samples = [{"name": r["name"], "home": home(f, r["owner"])} for f, r in hits[:3]]
        return {"count": len(hits), "homes": len(homes), "samples": samples}
    return {"name": row["name"], "nodes": row["nodes"],
            "nb": twins(nb_index, row["nb"]), "st": twins(st_index, row["st"])}

out = {"corpus": {"files": len(rows_by_file),
                  "yulFnRows": sum(len(r) for r in rows_by_file.values())},
       "subjects": []}
for label, fname in subjects:
    seen, fns = set(), []
    for row in rows_by_file[fname]:
        if ":ir:" not in row["owner"] or row["name"] in seen:
            continue
        seen.add(row["name"])
        fns.append(classify(fname, row))
    fns.sort(key=lambda f: (f["nb"]["count"], f["st"]["count"], -f["nodes"]))
    meta = {"fartdog": {"address": "0x7A492a6CFbE89B8DB6Be0Dee13793b8A43B24443",
                        "pin": "0.8.34", "match": "exact_match", "note": "verified on mainnet 2026-06-12"},
            "EntryPoint": {"address": "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
                           "pin": "0.8.23", "match": "exact_match", "note": "ERC-4337 EntryPoint v0.7"},
            "Token": {"address": "0xc4ecA49aDd562b809eF9488a2Cb6C552377e9928",
                      "pin": "0.8.30", "match": "exact_match", "note": "verified on mainnet 2026-06-12"},
            }.get(label, {})
    out["subjects"].append({"label": label, **meta, "functions": fns,
                            "total": len(fns),
                            "machineryNB": sum(1 for f in fns if f["nb"]["count"] > 0),
                            "machineryST": sum(1 for f in fns if f["st"]["count"] > 0)})

with open(out_path, "w") as f:
    f.write("// Generated by generate-triage-data.py — do not hand-edit.\n")
    f.write("window.RIFFCAT_TRIAGE = ")
    json.dump(out, f, indent=1)
    f.write(";\n")
for s in out["subjects"]:
    print(f"{s['label']}: {s['total']} fns | names-blind machinery {s['machineryNB']} "
          f"(novel {s['total']-s['machineryNB']}) | structure machinery {s['machineryST']} "
          f"(novel {s['total']-s['machineryST']})", file=sys.stderr)
